# Generated by Django 5.2.12 on 2026-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15, unique=True)),
                ('breakfast', models.CharField(default='Not Set', max_length=255)),
                ('lunch', models.CharField(default='Not Set', max_length=255)),
                ('dinner', models.CharField(default='Not Set', max_length=255)),
            ],
        ),
    ]
