# Generated by Django 5.2.12 on 2026-04-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_category', models.CharField(choices=[('Food', 'Food'), ('Cleanliness', 'Cleanliness'), ('Maintenance', 'Maintenance'), ('Noise', 'Noise'), ('Facilities', 'Facilities'), ('Safety', 'Safety'), ('Other', 'Other')], max_length=20)),
                ('complaint_description', models.TextField()),
                ('poll_question', models.TextField()),
                ('poll_duration_days', models.IntegerField(choices=[(1, '1 day'), (3, '3 days'), (7, '7 days')])),
                ('poll_status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('vote_yes_count', models.IntegerField(default=0)),
                ('vote_no_count', models.IntegerField(default=0)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action_note', models.TextField(blank=True, null=True)),
                ('priority_flag', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=10)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_polls', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint_polls',
            },
        ),
        migrations.CreateModel(
            name='PollEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='poll_evidence/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.complaintpoll')),
            ],
            options={
                'db_table': 'poll_evidence',
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.complaintpoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poll_votes',
                'unique_together': {('poll', 'voter')},
            },
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
